name: analyze and test

# This workflow is triggered on pushes to the repository.

# Default will running for every branch.
on: push

jobs:
  build-and-test:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
      - run: flutter --version
      # Get flutter dependencies.
      - run: flutter pub get
      # Statically analyze the Dart code for any errors.
      - run: flutter analyze --no-fatal-infos
      # Run widget tests for our flutter project.
      - run: flutter test --coverage
      - name: 'Publish to coveralls.io'
        uses: coverallsapp/github-action@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
