name: Car Manager UI Continuous Delivery (Example App)

# This workflow automates the building and publishing of an APK for the Car Manager UI example application.
# It is triggered automatically when pushes are made to the 'develop' branch.

on:
  push:
    branches:
      - 'feature/CARMAN-314/cd_firebase_distribution'

jobs:
  build-and-test:
    name: Build and Publish Test APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Installs the specified version of Flutter in the environment.
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      # Prints the installed Flutter version to verify the setup.
      - name: Verify Flutter Version
        run: flutter --version

      # Compiles the Flutter application into a debug APK.
      - name: Build Test APK
        run: cd example && flutter build apk --debug

      # Upload APK to Firebase App Distribution
      - name: Distribute to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_TESTAPP_CM_UI }}
          serviceCredentialsFileContent: ${{ secrets.SERVICE_ACCOUNT_TESTAPP_CM_UI }}
          groups: "cm-testers"
          file: example/build/app/outputs/flutter-apk/app-debug.apk
          releaseNotes: "Test build (debug) generated on merge to develop."
